force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>Object to record executive interactions</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship with the entity User</description>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/AsignationDate__c.field-meta.xml
<CustomField>
    <fullName>AsignationDate__c</fullName>
    <description>Date/hour where an interaction changes form a queue to a user</description>
    <label>Asignation date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Interaction_Origin__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Origin__c</fullName>
    <label>Interaction Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IO001</fullName>
            </value>
            <value>
                <fullName>IO002</fullName>
            </value>
            <value>
                <fullName>IO003</fullName>
            </value>
            <value>
                <fullName>Canales Digitales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <description>Office</description>
    <inlineHelpText>Cola/oficina</inlineHelpText>
    <label>Office</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/QSF_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>QSF_Appointment_Id__c</fullName>
    <label>Appointment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/QSF_Reason__c.field-meta.xml
<CustomField>
    <fullName>QSF_Reason__c</fullName>
    <label>Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>reason</description>
    <inlineHelpText>Motivo</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>63</fullName>
            </value>
            <value>
                <fullName>66</fullName>
            </value>
            <value>
                <fullName>68</fullName>
            </value>
            <value>
                <fullName>69</fullName>
            </value>
            <value>
                <fullName>67</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>71</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
            <value>
                <fullName>73</fullName>
            </value>
            <value>
                <fullName>74</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>76</fullName>
            </value>
            <value>
                <fullName>77</fullName>
            </value>
            <value>
                <fullName>78</fullName>
            </value>
            <value>
                <fullName>79</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>BR01</fullName>
            </value>
            <value>
                <fullName>BR02</fullName>
            </value>
            <value>
                <fullName>BR03</fullName>
            </value>
            <value>
                <fullName>BR04</fullName>
            </value>
            <value>
                <fullName>BR05</fullName>
            </value>
            <value>
                <fullName>BR06</fullName>
            </value>
            <value>
                <fullName>ErrorCol_A</fullName>
            </value>
            <value>
                <fullName>ErrorCol_B</fullName>
            </value>
            <value>
                <fullName>ErrorCol_C</fullName>
            </value>
            <value>
                <fullName>81</fullName>
            </value>
            <value>
                <fullName>82</fullName>
            </value>
            <value>
                <fullName>83</fullName>
            </value>
            <value>
                <fullName>84</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status values for the interaction</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ESTA000</fullName>
            </value>
            <value>
                <fullName>ESTA001</fullName>
            </value>
            <value>
                <fullName>ESTA002</fullName>
            </value>
            <value>
                <fullName>ESTA003</fullName>
            </value>
            <value>
                <fullName>ESTA004</fullName>
            </value>
            <value>
                <fullName>ESTA005</fullName>
            </value>
            <value>
                <fullName>ESTA006</fullName>
            </value>
            <value>
                <fullName>STS003</fullName>
            </value>
            <value>
                <fullName>STS004</fullName>
            </value>
            <value>
                <fullName>STS005</fullName>
            </value>
            <value>
                <fullName>ESTA007</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <description>Ticket Number</description>
    <inlineHelpText>número de tiquet</inlineHelpText>
    <label>Ticket Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QSF_WS_InfoREST_Test.cls
@IsTest(SeeAllData=false) 
private class QSF_WS_InfoREST_Test {
    
    @isTest
    static void testDoPost() {
        // prepare test-data
        
        //As Per Best Practice it is important to instantiate the Rest Context
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = '/services/apexrest/QuendaInfo'; //Request URL
        request.httpMethod = 'POST';
        
        RestContext.request = request;
        RestContext.response= response;
        
        
        Interaction__c newInter = new Interaction__c();
 		newInter.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Interaction Chile').getRecordTypeId();
		newInter.AsignationDate__c = Datetime.valueOf('2018-01-23 13:00:00');
	    newInter.Office__c = 'CLPLX00';
	    newInter.Reason__c = '70';
	    newInter.Status__c = 'ESTA001';
	    newInter.TicketNumber__c = 'E003';
	    newInter.Interaction_Origin__c ='IO003';
	    newInter.QSF_Appointment_Id__c = '5';
	    newInter.QSF_Reason__c = 'Atención sin ticket';
        
        Interaction__c newInterError = newInter;
        newInterError.Agent__c = null;
        
        
        
        Test.startTest();
        QSF_WS_InfoREST.doPost(newInter);
        
        QSF_WS_InfoREST.doPost(newInterError);
        
        Test.stopTest();
        
        //System.assertEquals('expected value', actual, 'Value is incorrect');
    }
}